### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Lyon-CZ** [Kamikaze94/WolfHUD#184] opened 2017-02-25 10:07 UTC
PAYDAY 2 Crash log
Application has crashed: access violation
-------------------------------
Callstack:
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
-------------------------------
Current thread: Main
Script stack:
             _process_damage()  @mods/WolfHUD/lua/TabStats.lua:863                  
kpr_original_copdamage_ondamagereceived()  @mods/WolfHUD/lua/TabStats.lua:855                  
         _on_damage_received()  @mods/Keepers/lua/copdamage.lua:3                   
                 damage_fire()  lib/units/enemies/cop/copdamage.lua:1035            
         detect_and_give_dmg()  lib/managers/firemanager.lua:461                    
                  _do_damage()  lib/units/environment/environmentfire.lua:266       
                                lib/units/environment/environmentfire.lua:215       
-------------------------------
System information:
	Application version : 1.64.1
	CPU : Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 970M / nvd3dum.dll[21.21.13.7866]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16265MB 928KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Reproduktory (Realtek High Definition Audio))

**Comment by Kamikaze94** [comment] 2017-04-02 13:02
Most likely duplicate of issue #186, so this is hopefully fixed as well.
(Seems to be about fire damage as well...)

**Closed by Kamikaze94** 2017-04-02 13:02 UTC
