### ISSUE TITLE
Crash mid game - Something to do with an error with strings and tables

### ISSUE THREAD

**Issue by frostermrr** [Kamikaze94/WolfHUD#223] opened 2017-04-07 05:05 UTC
Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3: bad argument #3 to 'format' (string expected, got table)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlReAllocateHeap                                   

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.68.193
	CPU : Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 970M / nvd3dum.dll[21.21.13.7892]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16333MB 84KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by Kamikaze94** [comment] 2017-04-18 13:23
Duplicate of issue #163.

**Closed by Kamikaze94** 2017-04-18 13:23 UTC
Labels: duplicate
