### ISSUE TITLE
Crash, possibly on buffs?

### ISSUE THREAD

**Issue by JoeStaines** [Kamikaze94/WolfHUD#287] opened 2017-05-20 20:32 UTC
`Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3: bad argument #3 to 'format' (string expected, got table)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.71.243
	CPU : AMD FX(tm)-6300 Six-Core Processor (3 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 10.0 
	GPU : AMD Radeon R9 200 Series / aticfx32.dll[22.19.157.3]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16348MB 656KB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : VIA Technologies, Inc. (Speakers (VIA High Definition Audio))`

**Comment by Kamikaze94** [comment] 2017-05-23 18:40
Duplicate of issue #163.
Fixed in dev version.
Download: https://github.com/Kamikaze94/WolfHUD/archive/master.zip

**Closed** 2017-05-24 18:06 UTC
Labels: duplicate
