### ISSUE TITLE
crash every time swan song ends

### ISSUE THREAD

**Issue by TheLaw1473** [Kamikaze94/WolfHUD#219] opened 2017-03-31 19:36 UTC
first of all, you have a great mod but every time i die from swan song my game freeses for a few seconds and after that the game just crashes. i tried to redownload wolfhud but it didn't help. plz help me i love this mod so much.
[crashlog.txt](https://github.com/Kamikaze94/WolfHUD/files/886717/crashlog.txt)

**Comment by kuronekosaiko** [comment] 2017-04-01 05:25
[here's](http://disq.us/p/1h410rr) a way 2 fix this.


> Swan Song Crash?
> 
> * First, go to mods/WolfHUD/lua/GameInfoManager.lua
> * Open it up with a text editor. I'm using Notepad++
> * Locate the 386th line.
> * Delete 
> berserker_damage_multiplier = { "swan_song", "swan_song_aced" },
> * Do same thing for 3136 and 3137th lines.
> melee_damage_health_ratio_multiplier = { category = "melee", buff_id = "berserker" },
> damage_health_ratio_multiplier = { category = "damage", buff_id = "berserker_aced" },
> 
> Also, you can completely delete GameInfoManager for safebet, but you can't use HUD Infos either.

**Comment by NerdVenom** [comment] 2017-04-01 11:40
Either do as kuronekosaiko says, or just delete your version of WolfHUD and use the latest dev version found here : https://github.com/Kamikaze94/WolfHUD (Click the green "Clone or download" button then click "Download zip")

**Comment by TheLaw1473** [comment] 2017-04-01 14:29
It worked! Thank you!

**Comment by Kamikaze94** [comment] 2017-04-02 12:50
Duplicate of issue #163.

**Comment by FlamingFox911** [comment] 2017-04-03 20:02
You might also want to consider deleting your crashlog.txt file. The more you crash, the larger that file gets.

**Closed** 2017-10-28 22:07 UTC
Labels: duplicate
