### ISSUE TITLE
default hud down counter

### ISSUE THREAD

**Issue by Hulkfog** [Kamikaze94/WolfHUD#32] opened 2016-07-26 19:07 UTC
The detection rating doesn't seems to appear for other players
The down counter or risk indicator when joining mid game doesn't seem to show 0 downs or detection rating

**Comment by Kamikaze94** [comment] 2016-07-27 02:40
Okay, the script had a few bugs, mostly related to me changing around how the downs get counted...
I think its all fixed now, at least it seemed to work normal for me, during my (admitted: short) testing period.
I noticed, that the text gets almost invisible, while the player is interaction, because the text is part of the health panel... might need/want to change that.

As always thaks for reporting, and feel free to tell me, if there is anything still buggy I've overlooked  :)

**Comment by Hulkfog** [comment] 2016-07-27 19:54
As a client in stealth the main player risk indicator showed -1
if downed in stealth the risk indicator switches to to show downs

**Comment by Kamikaze94** [comment] 2016-07-28 01:27
That "-1" happened to me before too, when the risk got determined too early (before the player was spawned or something....)
Thats why its not a one-time-set anymore, and got replaced by an update if the current risk is not equal the last one...
Cannot confirm that bug happeneing to me anymore.
Not sure about the cause of that currently...
Oh, and the risk changing to downs, if you get downed in stealth, is intentional.

**Comment by Kamikaze94** [comment] 2016-08-05 01:21
So, the DownCounter Script for the default HUD is now in the same state as the CustomHUD version (kinda..), so I assume it should be working now.
Only tested it a little in a local game, so I cannot say for sure.
If you notice anything still bugging out, please tell me.
(I know that using your armor kit doesn't update the text, its the same if you use CustomHUD...)

**Comment by Hulkfog** [comment] 2016-08-05 19:48
Other players down counter shows ? until they get downed

**Comment by Kamikaze94** [comment] 2016-08-05 21:46
Actually, forgot the reset on name set, sso the reset, when a new player joins.   
(+ changed counter initialization)  
Should be working now....  :)

**Closed** 2016-08-06 19:52 UTC
Labels: bug, fixxed
