### ISSUE TITLE
Giant pick-up icons for first-person player

### ISSUE THREAD

**Issue by Malidictus** [Kamikaze94/WolfHUD#47] opened 2016-08-29 14:32 UTC
I don't know when this started happening, but my pickup item icons (HCl, Mu, CS, planks, etc,) have become giant in my inventory when using CustomHud. A few days ago, they were small enough to where three can stack vertically before new ones have to shift to the right. Right now they're so large that a single pick-up covers the entire space so new ones always sit on the right. If I pick up enough stuff, they start running out of screen space to the right.

This only occurs for my own pick-ups display, however - the one in the bottom centre of the screen. The pick-ups for other players - displayed on the bottom left - are still of the correct size. I checked to see if a new scaling option hasn't snuck in behind my back, but the only one I found is for the entire player panel. I like the size of the player panel, it's just the pick-ups which are the wrong size.

I've been sick as a dog lately so my memory isn't that good, but I THINK I downloaded the new WolfHud with the spade/level/infamy fix yesterday at some point, which is when this started happening. Would I need to provide a screenshot?

**Comment by Tatsugi** [comment] 2016-08-29 14:47
WolfHUD Settings -> General HUD Panel Options -> Player Panel -> Special Equipment Rows
This option you need to configure, default (vanilla) 3.

**Comment by Kamikaze94** [comment] 2016-08-29 15:40
Tested it with different values, before creating the ingame option for that.
Actually forgot to reset it to 3, after I finished testing.
Thanks for mentioning, will fix that...^^

**Comment by Malidictus** [comment] 2016-08-29 15:51
Ah! Thank you, I never noticed that option before. I set it to 3 as advised and everything seems fine now. Sorry for the erroneous report. My problem is now fixed :)

**Comment by Kamikaze94** [comment] 2016-08-29 16:52
No need to feel sorry, it was my fault to leave 1 the default value...^^
So thanks for reporting, or I might have accidentally pushed the regula update with that at some point, xD
I'll close this now, as the problem is resolved.

**Closed by Kamikaze94** 2016-08-29 16:52 UTC
