### ISSUE TITLE
Using swan song makes the game crash

### ISSUE THREAD

**Issue by Poloski** [Kamikaze94/WolfHUD#181] opened 2017-02-25 00:50 UTC
Right after the effect of the skill is ended, the game freezes then crashes.
Tried on heists such as counterfeit, boiling point, and brooklyn 10-10

Fri Feb 24 21:40:56 2017

Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3: bad argument #3 to 'format' (string expected, got table)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.64.1
	CPU : Intel(R) Core(TM) i3 CPU 540 @ 3.07GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GT 610 / nvd3dum.dll[21.21.13.7653]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     3957MB 404KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Auriculares (Dispositivo de High Definition Audio))

**Comment by Nemesis1021** [comment] 2017-02-27 21:34
I have the same problem ... i dont know if its just some people , or everyone that uses this version.
Do you know where i can find the updated version? I actually dont know where to look sadly

**Comment by Kamikaze94** [comment] 2017-04-02 12:49
Duplicate of issue #163.

**Closed by Kamikaze94** 2017-04-02 12:49 UTC
