### ISSUE TITLE
CRASH when i go down by enemy damage - Swan Song CRASHLOG

### ISSUE THREAD

**Issue by Nyakuya** [Kamikaze94/WolfHUD#190] opened 2017-03-07 07:13 UTC
So, i have BLT and "Better Bots" Mod installed since 2 months ago, and i have 0 crashes.
Now i decide install this mod because it's a very awesome and beautiful mod, i love it in all aspects except one... When i fall down by enemy damage.

This situation repeated himself 3 and 4 times consecutive with NO exceptions, so i decide to put my ''grain of sand'' with the CRASHLOG.

You can get the .TXT file from here, 
[crashlog.txt](https://github.com/Kamikaze94/WolfHUD/files/823605/crashlog.txt)

Besides, matters or not, i will mention it. I have the ability of not fall down instantly, i don't remember the name (Swan Song), "Basic (3 pt): Instead of getting downed instantly, you gain the ability to keep fighting for 3 seconds with a 60% movement penalty before going down", "Ace (6 pt): Increases the duration for Swan Song by 6 seconds. Ammunition won't be depleted while the effect is active".

Please, if anyone can read the CRASHLOG and tell me what is the problem, i would be grateful, because i don't understand the log.

**Comment by Nyakuya** [comment] 2017-03-07 15:13
Ok. Temporal solution deleting 3 lines, (386, 3136 and 3137).

More info can be found here:
https://www.reddit.com/r/paydaytheheist/comments/5ui53q/u132_wolfhud_swan_song_crash_temporary_fix/

**Comment by FlamingFox911** [comment] 2017-03-16 03:49
I would also recommend downloading latest dev version [here](https://github.com/Kamikaze94/WolfHUD/archive/master.zip). It resolves this issue.

**Comment by Kamikaze94** [comment] 2017-04-02 12:49
Duplicate of issue #163.

**Closed by Kamikaze94** 2017-04-02 12:49 UTC
