### ISSUE TITLE
Swan Song Crash

### ISSUE THREAD

**Issue by otobot1** [Kamikaze94/WolfHUD#234] opened 2017-04-16 14:10 UTC
My game keeps crashing after swan song ends. 

System information:
	Application version : 1.68.209
	CPU : Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 970 / nvd3dum.dll[22.21.13.8165]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16327MB 64KB
	OS : 6.1.7601 (Service Pack 1) 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

----------------------------------------------------------------------

Sun Apr 16 03:48:59 2017

Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3: bad argument #3 to 'format' (string expected, got table)

**Comment by Jowy12** [comment] 2017-04-16 16:59
Download the Dev Version of WolfHUD. Click clone/download button from this site.

**Comment by Kamikaze94** [comment] 2017-04-18 13:23
Duplicate of issue #163.

**Closed** 2017-10-28 22:07 UTC
Labels: duplicate
