### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by rnudguts** [Kamikaze94/WolfHUD#178] opened 2017-02-20 17:50 UTC
Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3: bad argument #3 to 'format' (string expected, got table)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlReAllocateHeap                                   
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.64.1
	CPU : Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 770M / nvd3dum.dll[10.18.13.6869]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16105MB 60KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

Level: Cookoff
Difficulty: Overkill
Had just finished 9 second swan song and crashed before going down
hopefully this will help

**Comment by Jowy12** [comment] 2017-02-21 06:03
Try download and install the dev version of WolfHUD. I've been using the Dev version and no crash at all.

**Comment by Aruzeus** [comment] 2017-02-23 15:37
Hey i had the same problem, and i found this fix : [https://steamcommunity.com/app/218620/discussions/15/135509472107529805/#c135509472107919308](url)

1. Go into your mod Folder
2. Open WolfHUD Folder -> Lua Folder -> GameInfoManager with Texteditor.
3. Search for this Line
  " berserker_damage_multiplier = { "swan_song", "swan_song_aced" },"
4. Delete it or put it in comment 
5. Test it :p

**Comment by Kamikaze94** [comment] 2017-04-02 12:48
Duplicate of issue #163.

**Closed by Kamikaze94** 2017-04-02 12:48 UTC
