### ISSUE TITLE
Restoration Mod prevents HudPanelList

### ISSUE THREAD

**Issue by rndash** [Kamikaze94/WolfHUD#1] opened 2016-04-11 22:07 UTC
If I try and run Restoration Mod alongside WolfHUD, most everything works fine aside from the HudPanelList part of WolfHUD, which simply does not show up at all, not even the vanilla hostage counter is there. There are no errors in my BLT logs on this conflict.

**Comment by Kamikaze94** [comment] 2016-04-12 14:21
Oh, it's a wonder you didn't crash, I guess, as Restoration beeing a LUA/BLT HUD itself.
So the rest does really work?
Btw, restoration is a HUD, aiming to make the games hud look like the alpha/beta version, right? Why would someone install that, and then install a hud mod, that does the exact oppsite, kinda, by adding more info and stuff? I wonder, if you have a good reason for that,  ;P
So in short, making it compatible wouldn't be easy, and isn't really needed (Unless you can convince me, ^^).
Thanks for reporting anyways.

**Comment by rndash** [comment] 2016-04-12 20:54
The HUD is just a part of Restoration Mod, and I have the HUD part disabled, which I should have mentioned in the first place. I mainly use Restoration Mod for the changes it makes to the main menu, crimenet, the contractor briefing screen, and the black screen before heists. But these are all just cosmetic changes, so if it is much work for you, I completely understand if you'd rather not deal with it.

**Comment by Kamikaze94** [comment] 2016-04-18 22:47
Okay, I read about that problem on Payday 2 forums on Steam.
http://steamcommunity.com/app/218620/discussions/15/368542844485455444/
It is caused by Restoration by hard overwriting the HUDManager:_setup_player_info_hud_pd2(), when Restoration loads after the HUDList script.
I added a PostHook, that should fix the issue.
It would be nice, if you could test it out and report back, how it worked out.
Thanks!  : D

**Comment by rndash** [comment] 2016-04-19 01:29
Unfortunately, your fix didn't work. However, I used Seven's fix from the thread you linked, the one that made changes to Restoration Mod's code, and both mods work perfect together now from what I've seen so far. So thank you for linking it.

**Comment by Kamikaze94** [comment] 2016-05-17 00:33
Okay, I cannot find a way to fix this from my side, except maybe moving to a completely other function to hook this.
This isn't really a solution, so it can only be fixxed by the dev of Restoration mod.
Closing this now.

**Closed by Kamikaze94** 2016-05-17 00:33 UTC
Labels: cannot fix
