### ISSUE TITLE
Crashing after swan song fades

### ISSUE THREAD

**Issue by firstnecron** [Kamikaze94/WolfHUD#173] opened 2017-02-19 06:10 UTC
After swan song expires, I crash with the error: 

Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3: bad argument #3 to 'format' (string expected, got table)

**Comment by renuschd** [comment] 2017-02-23 05:33
this is fixed in the dev version so if you download it from here(github) and install it it'll fix

**Comment by Kamikaze94** [comment] 2017-04-02 12:48
Duplicate of issue #163.

**Closed by Kamikaze94** 2017-04-02 12:48 UTC
